packages:
  - "apps/*"
  - "packages/*"
onlyBuiltDependencies:
  - core-js
  - esbuild
  - protobufjs
  - sharp

overrides:
  esbuild: 0.27.0
  react: 19.2.3
  react-dom: 19.2.3
  react-test-renderer: 19.2.3
  react-native: 0.86.2
